// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.4
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Order.Api.Application.Events
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class ReserveItems : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""ReserveItems"",""namespace"":""Order.Api.Application.Events"",""fields"":[{""name"":""OrderId"",""type"":""string""},{""name"":""products"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""ReserveItemProduct"",""namespace"":""Order.Api.Application.Events"",""fields"":[{""name"":""id"",""type"":""string""},{""name"":""Quantity"",""type"":""int""}]}}}]}");
		private string _OrderId;
		private IList<Order.Api.Application.Events.ReserveItemProduct> _products;
		public virtual Schema Schema
		{
			get
			{
				return ReserveItems._SCHEMA;
			}
		}
		public string OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				this._OrderId = value;
			}
		}
		public IList<Order.Api.Application.Events.ReserveItemProduct> products
		{
			get
			{
				return this._products;
			}
			set
			{
				this._products = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.OrderId;
			case 1: return this.products;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.OrderId = (System.String)fieldValue; break;
			case 1: this.products = (IList<Order.Api.Application.Events.ReserveItemProduct>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
